#!/bin/bash

# See
# https://github.com/awslabs/amazon-ecr-credential-helper

set -e

source "$BASH_HELPERS"

# =============================================================================

readonly TMP_DIR=$(mktemp --tmpdir=/tmp --directory ecr-helper-XXXXXXXX)

readonly SYSTEM_BIN_DIR="/usr/local/bin"

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_NAME="$(basename "$0")"

# =============================================================================

function print_usage {
  echo
  echo "Usage: install-ecr-helper [OPTIONS]"
  echo
  echo "This script can be used to install Amazon ECR Credential Helper on AWS EC2."
  echo
  echo "Options:"
  echo
  echo -e "  --version\tThe version of Amazon ECR Credential Helper to install."
  echo
  echo "Example:"
  echo
  echo "  install-ecr-helper --version 0.4.0"
}

# =============================================================================

function install_ecr_helper {
  local readonly version="$1"
  local readonly arch=$(dpkg --print-architecture)

  local readonly download_url="https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/$version/linux-$arch/docker-credential-ecr-login"
  local readonly download_path="$TMP_DIR/docker-credential-ecr-login"

  http_download "$download_url" "$download_path"
  sudo install "$download_path" "$SYSTEM_BIN_DIR"
}

# =============================================================================

function install {
  local version=""

  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --version)
        version="$2"
        shift
        ;;
      --help)
        print_usage
        exit
        ;;
      *)
        log_error "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  assert_not_empty "--version" "$version"

  log_info "Start installing Amazon ECR Credential Helper $version"

  install_ecr_helper "$version"

  log_info "Amazon ECR Credential Helper $version install complete!"
}

install "$@"
