#!/bin/bash

# See
# https://docs.docker.com/compose/install/

set -e

source "$BASH_HELPERS"

# =============================================================================

readonly TMP_DIR=$(mktemp --tmpdir=/tmp --directory docker-compose-XXXXXXXX)

readonly SYSTEM_BIN_DIR="/usr/local/bin"

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_NAME="$(basename "$0")"

# =============================================================================

function print_usage {
  echo
  echo "Usage: install-docker-compose [OPTIONS]"
  echo
  echo "This script can be used to install Docker Compose on AWS EC2."
  echo
  echo "Options:"
  echo
  echo -e "  --version\tThe version of Docker Compose to install."
  echo
  echo "Example:"
  echo
  echo "  install-docker-compose --version 1.27.3"
}

# =============================================================================

function install_docker_compose {
  local readonly version="$1"

  local readonly download_url="https://github.com/docker/compose/releases/download/$version/docker-compose-$(uname -s)-$(uname -m)"
  local readonly download_path="$TMP_DIR/docker-compose"

  http_download "$download_url" "$download_path"
  sudo install "$download_path" "$SYSTEM_BIN_DIR"
}

# =============================================================================

function install {
  local version=""

  while [[ $# > 0 ]]; do
    local key="$1"

    case "$key" in
      --version)
        version="$2"
        shift
        ;;
      --help)
        print_usage
        exit
        ;;
      *)
        log_error "Unrecognized argument: $key"
        print_usage
        exit 1
        ;;
    esac

    shift
  done

  assert_not_empty "--version" "$version"

  log_info "Start installing docker-compose $version"

  install_docker_compose "$version"

  log_info "Docker Compose $version install complete!"
}

install "$@"
