#!/bin/bash
set -x

source "$BASH_HELPERS"

assert_not_empty "OPEN_DISTRO_FOR_ELASTICSEARCH_VERSION" "$OPEN_DISTRO_FOR_ELASTICSEARCH_VERSION"

readonly INSTALL_PATH="/opt/elasticsearch"
readonly SCRIPT_DIR="/tmp"

function create_install_paths_and_binary() {
  local readonly run_path="$INSTALL_PATH/run-elasticsearch"
  sudo mkdir -p "$INSTALL_PATH"
  sudo cp -vf "$SCRIPT_DIR/run-elasticsearch" "$run_path"
  sudo chmod a+x "$run_path"
}

function install() {
  create_install_paths_and_binary
  # for Open Distro for Elasticsearch
  # see https://opendistro.github.io/for-elasticsearch-docs/docs/install/deb/
  wget -qO - https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch | sudo apt-key add -
  echo "deb https://d3g5vo6xdbdb9a.cloudfront.net/apt stable main" | sudo tee -a /etc/apt/sources.list.d/opendistroforelasticsearch.list

  local readonly download_url="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-6.7.1.deb"
  local readonly download_path="/tmp/$(basename "$download_url")"
  http_download "$download_url" "$download_path"
  sudo dpkg -i "$download_path"
  sudo apt-get update -y

  echo "Installing opendistroforelasticsearch version $OPEN_DISTRO_FOR_ELASTICSEARCH_VERSION"
  sudo apt-get install -y opendistroforelasticsearch=$OPEN_DISTRO_FOR_ELASTICSEARCH_VERSION

  sudo gpasswd -a $USER elasticsearch
}

install
